---
title: "Reproducible documents"
author: "Henriette Nymark Friis"
format: html

---

1. Henriette Nymark Friis
2. Department of Clinical Biochemistry

# Intro

**cool**

*Super cool*

# Methods and results


## Analysis

**cool**

*Super cool*

# Discussion

**cool**

*Super cool*

```{r}
2+2
```



```{r setup}
#| message: false
#| warning: false
library(tidyverse)
library(NHANES)
nhanes_small <- read_csv(here::here("data/NHANES_small.csv"))
```

```{r}
nhanes_small <- select(nhanes_small, age, sex, bmi, diabetes, phys_active, bp_sys_ave, bp_dia_ave, education)
nhanes_small
```

#Table of results

```{r}
#| warning: false
nhanes_small %>%
  filter(!is.na(diabetes)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  knitr::kable(caption = "Mean values of age and BMI for each education and diabetes status")
```


##Prettier table

```{r}
#| echo: false
#| warning: false
nhanes_small %>%
  filter(!is.na(diabetes), !is.na(education)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(
    # Task 2a.
    mean_age = round(mean_age, 1),
    mean_bmi = round(mean_bmi, 1), 
    # Task 2b.
    education = str_to_sentence(education)
  ) %>% 
  rename(
    # Task 3.
    "Diabetes status" = diabetes,
    "Education" = education,
    "Mean Age" = mean_age,
    "Mean BMI" = mean_bmi
  ) %>% 
  knitr::kable(caption = "Mean values of Age and BMI for each education and diabetes status.")
   
```


